# Generated by Django 3.2.2 on 2021-05-20 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ensembl.production.djcore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionApp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=255, verbose_name='App display name')),
                ('app_is_framed', models.BooleanField(default=True, help_text='Need an url then', null=True, verbose_name='Display app in iframe')),
                ('app_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='App flask url')),
                ('app_theme', models.CharField(choices=[('336', 'Ensembl'), ('707080', 'Bacteria'), ('714486', 'Protists'), ('407253', 'Plants'), ('725A40', 'Fungi'), ('015365', 'Metazoa'), ('800066', 'Datachecks')], default='FFFFFF', max_length=6)),
                ('app_prod_url', models.CharField(max_length=200, unique=True, verbose_name='App Url')),
                ('app_config_params', models.JSONField(blank=True, null=True, verbose_name='Configuration parameters')),
                ('app_groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productionapp_created_by', related_query_name='productionapp_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productionapp_modified_by', related_query_name='productionapp_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Admin',
                'verbose_name_plural': 'Apps Admin',
                'db_table': 'flask_app',
            },
        ),
        migrations.CreateModel(
            name='AppView',
            fields=[
            ],
            options={
                'verbose_name': 'Production Service',
                'verbose_name_plural': 'Production Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ensembl_prodinf_portal.productionapp',),
        ),
    ]
