# Generated by Django 3.2.2 on 2021-05-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_prodinf_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productionapp',
            table='production_app',
        ),
    ]
