# Generated by Django 3.2.11 on 2022-01-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_prodinf_portal', '0003_app_relative_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionapp',
            name='app_config_params',
        ),
        migrations.AlterField(
            model_name='productionapp',
            name='app_theme',
            field=models.CharField(choices=[('17a2b8', 'Ensembl'), ('007bff', 'Metazoa'), ('6c757d', 'Microbes'), ('28a745', 'Plants'), ('770f31', 'Rapid'), ('17a2b8', 'Vertebrates'), ('8552c0', 'Viruses'), ('ff9900', 'Gifts'), ('17a2b8', 'Production')], default='FFFFFF', max_length=6),
        ),
    ]
