# Generated by Django 3.2.18 on 2023-04-14 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ensembl.production.djcore.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ensembl_prodinf_portal', '0004_remove_app_js_param_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDatabaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('name', models.CharField(max_length=20)),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alloweddatabasemodel_created_by', related_query_name='alloweddatabasemodel_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alloweddatabasemodel_modified_by', related_query_name='alloweddatabasemodel_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allowed_databases',
            },
        ),
        migrations.AddField(
            model_name='productionapp',
            name='allowed_data_types',
            field=models.ManyToManyField(blank=True, to='ensembl_prodinf_portal.AllowedDatabaseModel'),
        ),
    ]
