# Generated by Django 3.2.19 on 2023-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_prodinf_portal', '0004_remove_app_js_param_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionapp',
            name='app_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='App flask url'),
        ),
    ]
