# Generated by Django 2.2.8 on 2020-01-23 16:02

from django.db import migrations

def remove_app_admin(apps, schema_editor):
    TreeItem = apps.get_model('sitetree', 'TreeItem')
    for record in TreeItem.objects.filter(url__startswith='/app/admin/'):
        record.url = record.url.replace('/app/admin/', '/admin/')
        record.save()


def reverse_app_admin(apps, schema_editor):
    TreeItem = apps.get_model('sitetree', 'TreeItem')
    for record in TreeItem.objects.filter(url__startswith='/admin/'):
        record.url = record.url.replace('/admin/', '/app/admin/')
        record.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_production', '0005_update_flask_apps')
    ]

    operations = [
        migrations.RunPython(remove_app_admin, reverse_app_admin),
    ]
