# Generated by Django 2.1.11 on 2020-02-14 16:29

import jsonfield
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_prodinf_portal', '0007_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionflaskapp',
            name='app_config_params',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Configuration parameters'),
        ),
        migrations.AddField(
            model_name='productionflaskapp',
            name='app_is_framed',
            field=models.BooleanField(default=True, help_text='Need an url then', null=True,
                                      verbose_name='Display app in iframe'),
        ),
        migrations.AlterField(
            model_name='productionflaskapp',
            name='app_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='App flask url'),
        ),
    ]
