# Generated by Django 2.2.13 on 2020-06-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_prodinf_portal', '0008_web_app_params'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionflaskapp',
            options={'verbose_name': 'Production App', 'verbose_name_plural': 'Production Apps'},
        ),
    ]
