# Generated by Django 2.1.7 on 2019-09-18 15:38

import django.db.models.deletion
import ensembl.production.portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_prodinf_portal', '0009_meta_option'),
    ]
    # TODO migrate all apps when possible with fake_initial to add migrations tables in required DBs.
    operations = [
    ]
