# Generated by Django 3.1.7 on 2021-04-01 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ensembl.production.djcore.models
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_prodinf_portal', '0009_meta_option'),
    ]

    operations = [
        migrations.RenameModel('ProductionFlaskApp', 'ProductionApp'),
        migrations.RunSQL(
            sql="UPDATE django_content_type "
                "SET app_label = 'ensembl_prodinf_portal' "
                "WHERE app_label = 'ensembl_production'",
            reverse_sql="UPDATE django_content_type "
                        "SET app_label = 'ensembl_production' "
                        "WHERE app_label = 'ensembl_prodinf_portal'",
        ),
        migrations.RunSQL(
            sql="DELETE FROM django_content_type "
                "WHERE app_label = 'ensembl_production_api'",
        ),
        migrations.RunSQL(
            sql="RENAME TABLE ensembl_production_credentials TO ensembl_jira_jiracredentials",
            reverse_sql="RENAME TABLE ensembl_jira_jiracredentials TO ensembl_production_credentials",
        ),
    ]
