language: python
os: linux
dist: xenial
python:
  - "3.7"
  - "3.6"
  - "3.5"
services:
  - mysql
env:
  - DJANGO=2.2.13 DB=mysql DEBUG=f
before_script:
  - mysql -u root -e "CREATE USER 'ensembl'@'localhost' IDENTIFIED BY '';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'ensembl'@'localhost';"
install:
  - pip install -r requirements.txt
  - pip install coverage==4.5.1
script:
  - coverage run --source='.' src/manage.py test ensembl.production.portal.tests
