version: '3.3'
services:
  production_portal_app:
    build: .
    container_name: productionportal
    env_file:
      - ./bin/.env
    ports:
      - '8000:8000'
    extra_hosts:
      - 'mysql-ens-general-dev-1:1.1.1.1'
    networks:
      - productionsrv  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    environment:
      - APP_HOST_URL=http://productionportal:8000 
    ports:
      - '80:80'
    depends_on:
      - production_portal_app
    networks:
      - productionsrv
networks:
  productionsrv:
    driver: bridge
