version: '3.3'
services:
  production_portal_app:
    build: .
    container_name: productionportal
    env_file:
      - ./bin/.env
    ports:
      - '8000:8000'
    extra_hosts:
      - 'hx-cluster:10.3.15.218'
      - 'mysql-ens-hive-prod-1:10.42.34.23'
      - 'mysql-ens-hive-prod-2:10.42.33.112'
      - 'mysql-ens-general-dev-1:10.32.24.191'
      - 'mysql-ens-sta-1:10.32.24.198'
      - 'noah-login-01:10.7.95.60'
    networks:
      - productionsrv  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    environment:
      - APP_HOST_URL=http://productionportal:8000 
    ports:
      - '80:80'
    depends_on:
      - production_portal_app
    networks:
      - productionsrv

networks:
  productionsrv:
    driver: bridge