# Generated by Django 2.1.7 on 2019-06-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length')
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionFlaskApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, verbose_name='App display name')),
                ('app_url', models.URLField(max_length=255, verbose_name='App flask url')),
                ('app_theme', models.CharField(choices=[('336', 'Ensembl'), ('707080', 'Bacteria'), ('714486', 'Protists'), ('407253', 'Plants'), ('725A40', 'Fungi'), ('015365', 'Metazoa'), ('800066', 'Datachecks')], default='FFFFFF', max_length=6)),
                ('app_prod_url', models.CharField(max_length=200, unique=True, verbose_name='App Url')),
                ('app_groups', models.ManyToManyField(to='auth.Group', blank=True, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Flask App',
                'verbose_name_plural': 'Flask Apps',
                'db_table': 'flask_app',
            },
        ),
    ]
