# Generated by Django 2.1.7 on 2019-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production', '0002_help_record_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionflaskapp',
            name='app_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
