# Generated by Django 2.2.7 on 2019-11-22 13:08
from django.core.management import call_command
from django.db import migrations
from ensembl_production.models import ProductionFlaskApp

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'ensembl_production/fixtures/elastic_hq.json', app_label='ensembl_production')


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production', '0004_insert_site_tree'),
    ]

    operations = [
        # migrations.RunPython(load_fixture),

    ]
