# Generated by Django 2.2.8 on 2020-01-23 16:02

from django.db import migrations

from django.conf import settings

default_db_name = settings.DATABASES['default']['NAME']


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_production', '0005_update_flask_apps')
    ]

    operations = [
        migrations.RunSQL("UPDATE `" + default_db_name + "`.sitetree_treeitem "
                          "SET url = REPLACE(url, '/app/admin/', '/admin/') WHERE url LIKE '/app/admin/%';"),
        migrations.RunSQL("DELETE FROM `" + default_db_name + "`.flask_app WHERE app_prod_url = 'admin';")
    ]
