# Generated by Django 2.1.7 on 2019-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metakey',
            name='is_multi_value',
            field=models.BooleanField(default=False),
        ),
    ]
