# Generated by Django 2.1.7 on 2019-04-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ensembl_production.models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdescription',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysisdescription_created_by', related_query_name='analysisdescription_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisdescription',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysisdescription_modified_by', related_query_name='analysisdescription_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattrib',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterattrib_created_by', related_query_name='masterattrib_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattrib',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterattrib_modified_by', related_query_name='masterattrib_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattribset',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterattribset_created_by', related_query_name='masterattribset_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattribset',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterattribset_modified_by', related_query_name='masterattribset_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattribtype',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='masterattribtype',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterattribtype_created_by', related_query_name='masterattribtype_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterattribtype',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterattribtype_modified_by', related_query_name='masterattribtype_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterbiotype',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterbiotype_created_by', related_query_name='masterbiotype_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterbiotype',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterbiotype_modified_by', related_query_name='masterbiotype_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterexternaldb',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterexternaldb_created_by', related_query_name='masterexternaldb_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterexternaldb',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterexternaldb_modified_by', related_query_name='masterexternaldb_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mastermiscset',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastermiscset_created_by', related_query_name='mastermiscset_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mastermiscset',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastermiscset_modified_by', related_query_name='mastermiscset_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterunmappedreason',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterunmappedreason_created_by', related_query_name='masterunmappedreason_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterunmappedreason',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterunmappedreason_modified_by', related_query_name='masterunmappedreason_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metakey',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metakey_created_by', related_query_name='metakey_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metakey',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metakey_modified_by', related_query_name='metakey_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='created_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webdata_created_by', related_query_name='webdata_creates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='modified_by',
            field=ensembl_production.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webdata_modified_by', related_query_name='webdata_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='web_data',
            field=models.TextField(db_column='`data`', null=True),
        ),
    ]
