# Generated by Django 2.1.7 on 2019-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webdata',
            old_name='web_data',
            new_name='data'
        )
    ]
