# Generated by Django 2.1.7 on 2019-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdata',
            name='web_data',
        ),
        migrations.AddField(
            model_name='webdata',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
