# Generated by Django 2.1.7 on 2019-10-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0002_auto_20190924_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterattrib',
            unique_together={('attrib_type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='masterattribset',
            unique_together={('attrib_set_id', 'attrib')},
        ),
    ]
