# Generated by Django 2.1.15 on 2020-02-06 13:32

from django.db import migrations
import ensembl_production_db.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0004_json_field_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdescription',
            name='description',
            field=ensembl_production_db.models.NullTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterattribtype',
            name='description',
            field=ensembl_production_db.models.NullTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterbiotype',
            name='description',
            field=ensembl_production_db.models.NullTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterexternaldb',
            name='description',
            field=ensembl_production_db.models.NullTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metakey',
            name='description',
            field=ensembl_production_db.models.NullTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='comment',
            field=ensembl_production_db.models.NullTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
