# Generated by Django 2.2.10 on 2020-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_production_db', '0006_external_db_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakey',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='metakey',
            unique_together={('name', 'is_optional', 'is_current')},
        ),
        migrations.RunSQL(
            'alter table meta_key add unique meta_key_unique_together(is_current, is_optional, name);',
            hints={'target_db': "ensembl_production_db"})
    ]
