# Generated by Django 2.1.7 on 2019-04-23 13:01
import django_mysql.models
from django.conf import settings
from django.db import migrations, models

from ensembl_production.models import SpanningForeignKey


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpLink',
            fields=[
                ('help_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_url', django_mysql.models.SizedTextField(blank=True, null=True, size_class=1)),
            ],
            options={
                'db_table': 'help_link',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HelpRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('help_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('keyword', django_mysql.models.SizedTextField(blank=True, null=True, size_class=1)),
                ('data', models.TextField()),
                ('status',
                 django_mysql.models.EnumField(choices=[('draft', 'draft'), ('live', 'live'), ('dead', 'dead')])),
                ('helpful', models.IntegerField(blank=True, null=True)),
                ('not_helpful', models.IntegerField(blank=True, null=True)),
                ('created_by', SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False,
                                                  null=True, on_delete=models.SET_NULL,
                                                  related_name='masterattribset_created_by',
                                                  related_query_name='masterattribset_creates',
                                                  to=settings.AUTH_USER_MODEL)),
                ('modified_by', SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False,
                                                   null=True, on_delete=models.SET_NULL,
                                                   related_name='masterattribset_modified_by',
                                                   related_query_name='masterattribset_updates',
                                                   to=settings.AUTH_USER_MODEL)),

            ],
            options={
                'db_table': 'help_record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaqRecord',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ',
                'proxy': True,
                'indexes': [],
            },
            bases=('ensembl_website.helprecord',),
        ),
        migrations.CreateModel(
            name='LookupRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Lookup',
                'proxy': True,
                'indexes': [],
            },
            bases=('ensembl_website.helprecord',),
        ),
        migrations.CreateModel(
            name='MovieRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Movie',
                'proxy': True,
                'indexes': [],
            },
            bases=('ensembl_website.helprecord',),
        ),
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Page',
                'proxy': True,
                'indexes': [],
            },
            bases=('ensembl_website.helprecord',),
        ),
    ]
