# Generated by Django 2.1.7 on 2019-09-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helplink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='helprecord',
            options={},
        ),
    ]
