# Generated by Django 2.1.15 on 2020-02-06 13:32

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_website', '0003_auto_20190924_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helplink',
            name='page_url',
            field=django_mysql.models.SizedTextField(null=True, size_class=1),
        ),
    ]
