# Generated by Django 2.2.13 on 2020-11-19 16:44

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_website', '0004_make_page_url_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprecord',
            name='status',
            field=django_mysql.models.EnumField(choices=[('draft', 'Draft'), ('live', 'Live'), ('dead', 'Dead')]),
        ),
    ]
