# Generated by Django 2.1.7 on 2019-11-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbs2Exclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.CharField(db_column='TABLE_SCHEMA', max_length=64)),
            ],
            options={
                'db_table': 'dbs_2_exclude',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebugLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=128, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('function', models.CharField(blank=True, max_length=128, null=True)),
                ('value', models.CharField(blank=True, max_length=8192, null=True)),
            ],
            options={
                'db_table': 'debug_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestJob',
            fields=[
                ('job_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('src_host', models.CharField(max_length=2048)),
                ('src_incl_db', models.CharField(blank=True, max_length=2048, null=True)),
                ('src_skip_db', models.CharField(blank=True, max_length=2048, null=True)),
                ('src_incl_tables', models.CharField(blank=True, max_length=2048, null=True)),
                ('src_skip_tables', models.CharField(blank=True, max_length=2048, null=True)),
                ('tgt_host', models.CharField(max_length=2048)),
                ('tgt_db_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('tgt_directory', models.CharField(blank=True, max_length=2048, null=True)),
                ('skip_optimize', models.IntegerField(blank=True, null=True)),
                ('wipe_target', models.IntegerField(blank=True, null=True)),
                ('convert_innodb', models.IntegerField(blank=True, null=True)),
                ('email_list', models.CharField(blank=True, max_length=2048, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'request_job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('job_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('tgt_host', models.CharField(max_length=512)),
                ('table_schema', models.CharField(db_column='TABLE_SCHEMA', max_length=64)),
                ('table_name', models.CharField(db_column='TABLE_NAME', max_length=64)),
                ('renamed_table_schema', models.CharField(max_length=64)),
                ('target_directory', models.CharField(blank=True, max_length=2048, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfer_log',
                'managed': False,
            },
        ),
    ]
