# Generated by Django 2.2.8 on 2019-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='user',
            new_name='mysql_user',
        ),
        migrations.AddField(
            model_name='transferlog',
            name='message',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='retries',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
