# Generated by Django 2.2.13 on 2020-06-08 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestjob',
            options={'verbose_name': 'Copy job', 'verbose_name_plural': 'Copy jobs'},
        ),
        migrations.AddField(
            model_name='requestjob',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
