# Generated by Django 2.1.15 on 2020-02-06 13:59

from django.db import migrations
import ensembl_dbcopy.models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0002_auto_20191217_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestjob',
            name='src_incl_db',
            field=ensembl_dbcopy.models.NullTextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_incl_tables',
            field=ensembl_dbcopy.models.NullTextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_skip_db',
            field=ensembl_dbcopy.models.NullTextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_skip_tables',
            field=ensembl_dbcopy.models.NullTextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='tgt_db_name',
            field=ensembl_dbcopy.models.NullTextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='tgt_directory',
            field=ensembl_dbcopy.models.NullTextField(blank=True, max_length=2048, null=True),
        ),
    ]
