# Generated by Django 2.1.15 on 2020-02-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0003_text_field_null_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(choices=[('Vertebrates', 'Vertebrates'), ('Microbes', 'Microbes'), ('Metazoa', 'Metazoa'), ('VectorBase', 'VectorBase'), ('Plants', 'Plants'), ('WormBase', 'WormBase'), ('Compara', 'Compara'), ('Production', 'Production')], default='Vertebrates', max_length=80)),
                ('host_id', models.ForeignKey(db_column='auto_id', on_delete=django.db.models.deletion.CASCADE, to='ensembl_dbcopy.Host')),
            ],
            options={
                'verbose_name': 'Group',
                'db_table': 'group',
            },
        ),
    ]
