# Generated by Django 2.2.13 on 2021-01-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0003_add_dry_run_fix_dbs_2_exclude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Host Group'},
        ),
        migrations.AddField(
            model_name='host',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=80, verbose_name='User Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='host_id',
            field=models.ForeignKey(db_column='auto_id', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ensembl_dbcopy.Host'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mysqld_file_owner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
