# Generated by Django 2.2.13 on 2021-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0004_auto_20210129_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetHostGroup',
            fields=[
                ('target_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_group_name', models.CharField(max_length=80, unique=True, verbose_name='Hosts Group')),
                ('target_host', models.ManyToManyField(to='ensembl_dbcopy.Host')),
            ],
            options={
                'verbose_name': 'Hosts Target Group',
                'db_table': 'target_host_group',
            },
        ),
    ]
