# Generated by Django 2.2.13 on 2020-08-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraFakeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'jira',
            },
        ),
        migrations.CreateModel(
            name='Intention',
            fields=[
            ],
            options={
                'verbose_name': 'Release Intentions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ensembl_intentions.jirafakemodel',),
        ),
        migrations.CreateModel(
            name='KnownBug',
            fields=[
            ],
            options={
                'verbose_name': 'Known bug',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ensembl_intentions.jirafakemodel',),
        ),
    ]
